version: '3.7'
services:
  postgresql:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - env/db.env
    ports:
      - "5432:5432"
    restart: always

  bot:
    build:
      context: .
      dockerfile: docker/bot.Dockerfile
    env_file:
      - env/bot.env
    depends_on:
      - postgresql
    volumes:
      - ./bot:/code

volumes:
  postgres_data:
