"""Async init

Revision ID: 056d97f95d02
Revises: 
Create Date: 2023-06-29 15:06:40.056948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "056d97f95d02"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dares",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("dare", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_dares_id"), "dares", ["id"], unique=False)
    op.create_index(op.f("ix_dares_rating"), "dares", ["rating"], unique=False)
    op.create_table(
        "truth_questions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("question", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_truth_questions_id"), "truth_questions", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_truth_questions_rating"), "truth_questions", ["rating"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("discord_id", sa.BigInteger(), nullable=False),
        sa.Column("bad_words", sa.String(), nullable=True),
        sa.Column("lives", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("discord_id"),
    )
    op.create_index(op.f("ix_users_discord_id"), "users", ["discord_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_discord_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_truth_questions_rating"), table_name="truth_questions")
    op.drop_index(op.f("ix_truth_questions_id"), table_name="truth_questions")
    op.drop_table("truth_questions")
    op.drop_index(op.f("ix_dares_rating"), table_name="dares")
    op.drop_index(op.f("ix_dares_id"), table_name="dares")
    op.drop_table("dares")
    # ### end Alembic commands ###
