"""add role lock

Revision ID: a4d3dd091354
Revises: 056d97f95d02
Create Date: 2024-01-03 21:30:54.955441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4d3dd091354'
down_revision = '056d97f95d02'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role_lock', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role_lock')
    # ### end Alembic commands ###
